services:
  db:
    image: postgres:16
    container_name: postgres_db_dev
    environment:
      POSTGRES_DB: recette_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: spring_api_dev
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/recette_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      # C'est ici que la magie opère : on lie votre dossier local au conteneur
      - ./backend:/app
    depends_on:
      - db

volumes:
  postgres_data_dev:
