services:
  app:
    image: mcr.microsoft.com/devcontainers/base:debian-12
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - .env.dev
    volumes:
      - .:/workspaces/Application-recettes:cached
    depends_on:
      - db
