# Connexion Base de Donnees
spring.datasource.url=jdbc:postgresql://db:5432/recette_db
spring.datasource.username=user
spring.datasource.password=password

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update

# Parametres JWT
security.jwt.access-token-secret=change-me-access-token-secret-with-at-least-32-characters
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-secret=change-me-refresh-token-secret-with-at-least-32-characters
security.jwt.refresh-token-expiration=604800000
security.jwt.issuer=application-recettes-backend
security.jwt.audience=application-recettes-spa

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false

